pipeline {

    agent any


    environment {

        IMAGE_NAME = "saikiran9068/novapay"
        IMAGE_TAG = "latest"

        DOCKER = "/usr/local/bin/docker"
        KUBECTL = "/usr/local/bin/kubectl"

    }


    stages {


        stage('Checkout') {

            steps {

                echo "Checking source code"

            }

        }



        stage('Build') {

            steps {

                dir('app/novapay') {

                    sh '''

                    chmod +x mvnw

                    ./mvnw clean package

                    '''

                }

            }

        }



        stage('Unit Test') {

            steps {

                dir('app/novapay') {

                    sh '''

                    ./mvnw test

                    '''

                }

            }

        }




        stage('SAST - SonarQube') {

            steps {

                echo "Running SonarQube security scan"

            }

        }





        stage('Dependency Scan') {

            steps {

                echo "Checking vulnerable dependencies"

            }

        }





        stage('Docker Build') {

            steps {

                dir('app/novapay') {


                    sh '''

                    ${DOCKER} build \
                    -t ${IMAGE_NAME}:${IMAGE_TAG} .


                    '''


                }

            }

        }





        stage('Container Scan') {

            steps {


                sh '''

                trivy image \
                --severity HIGH,CRITICAL \
                --exit-code 0 \
                ${IMAGE_NAME}:${IMAGE_TAG}


                '''

            }

        }





        stage('Push Image') {


            steps {


                withCredentials([usernamePassword(
                    
                    credentialsId: 'dockerhub-token',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'

                )]) {


                    sh '''

                    echo $DOCKER_PASS | ${DOCKER} login \
                    -u $DOCKER_USER \
                    --password-stdin


                    ${DOCKER} push \
                    ${IMAGE_NAME}:${IMAGE_TAG}


                    '''


                }


            }

        }





        stage('Deploy Kubernetes') {


            steps {


                sh '''

                echo "Deploying Green Environment"


                ${KUBECTL} apply \
                -f app/novapay/kubernetes/green/deployment.yaml


                ${KUBECTL} apply \
                -f app/novapay/kubernetes/service.yaml



                ${KUBECTL} rollout status \
                deployment/novapay-green \
                -n novapay



                '''


            }


        }





        stage('Verification') {


            steps {


                sh '''

                echo "Checking Kubernetes Pods"


                ${KUBECTL} get pods \
                -n novapay



                ${KUBECTL} get svc \
                -n novapay


                '''


            }


        }


    }





    post {


        success {


            echo "Deployment completed successfully"


        }



        failure {


            echo "Deployment failed - initiating rollback"


            sh '''


            ${KUBECTL} rollout undo \
            deployment/novapay-green \
            -n novapay


            '''


        }


    }


}