pipeline {

    agent any

    environment {

        DOCKER_IMAGE = "saikiran9068/novapay:latest"

        DOCKER_USER = "saikiran9068"

        NAMESPACE = "novapay"

        TRIVY = "/usr/local/bin/trivy"

        DOCKER = "/usr/local/bin/docker"

        KUBECTL = "/usr/local/bin/kubectl"

    }


    stages {


        stage('Checkout') {

            steps {

                echo "Checking source code"

            }

        }



        stage('Build') {

            steps {

                dir('app/novapay') {

                    sh '''

                    chmod +x mvnw

                    ./mvnw clean package

                    '''

                }

            }

        }




        stage('Unit Test') {

            steps {

                dir('app/novapay') {

                    sh '''

                    ./mvnw test

                    '''

                }

            }

        }





        stage('SAST - SonarQube') {

            steps {

                echo "Running SonarQube security scan"

            }

        }




        stage('Dependency Scan') {

            steps {

                echo "Checking vulnerable dependencies"

            }

        }





        stage('Docker Build') {

            steps {

                dir('app/novapay') {

                    sh '''

                    ${DOCKER} build -t ${DOCKER_IMAGE} .

                    '''

                }

            }

        }





        stage('Container Scan') {

            steps {

                sh '''

                ${TRIVY} image \
                --severity HIGH,CRITICAL \
                --exit-code 0 \
                ${DOCKER_IMAGE}

                '''

            }

        }





        stage('Push Image') {

            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-token',
                        usernameVariable: 'USERNAME',
                        passwordVariable: 'PASSWORD'
                    )
                ]) {


                    sh '''

                    echo $PASSWORD | ${DOCKER} login \
                    -u $USERNAME \
                    --password-stdin


                    ${DOCKER} push ${DOCKER_IMAGE}

                    '''

                }

            }

        }






        stage('Deploy Kubernetes') {

            steps {


                sh '''

                ${KUBECTL} apply -f k8s/namespace.yaml

                ${KUBECTL} apply -f k8s/deployment.yaml

                ${KUBECTL} apply -f k8s/service.yaml


                ${KUBECTL} rollout status \
                deployment/novapay \
                -n ${NAMESPACE}


                '''

            }

        }






        stage('Verification') {

            steps {

                sh '''

                ${KUBECTL} get pods -n ${NAMESPACE}

                ${KUBECTL} get svc -n ${NAMESPACE}

                '''

            }

        }


    }





    post {


        success {

            echo "Deployment completed successfully"

        }




        failure {

            echo "Deployment failed - checking rollback"


            sh '''

            if ${KUBECTL} get deployment novapay -n ${NAMESPACE} >/dev/null 2>&1

            then

                ${KUBECTL} rollout undo \
                deployment/novapay \
                -n ${NAMESPACE}

            else

                echo "No deployment found. Rollback skipped."

            fi

            '''

        }


    }

}