apiVersion: v1
kind: Service

metadata:
  name: novapay-service
  namespace: novapay

spec:

  selector:
    app: novapay
    version: blue

  ports:

  - protocol: TCP
    port: 80
    targetPort: 8080

  type: NodePort